name: taskmaster
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  email_validator: ^2.1.17
  auto_route: ^7.8.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.7
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 400
